### ISSUE TITLE
Goal inference MH demo log-score animation is broken

### ISSUE THREAD

**Issue by marcoct** [probcomp/GenExperimental.jl#26]

**Comment by marcoct** [comment]
The log-score for the current trace that is shown does not seem correct. Needs to be debugged.

**Comment by marcoct** [comment]
I just removed it for now.

**Comment by mirisr** [comment]
Do you still want me to check it out?

**Comment by mirisr** [comment]
It was a javascript error. Replace Javascript function `add_score`  with:

`
function add_score(svg, trace) {
    var score = svg.selectAll(".score").data([""]);
    score.exit().remove();
    score.enter().append("text").classed("score", true).merge(score)
        .attr("x", 50).attr("y", 95)
        .text(function(d){return trace.log_weight.toFixed(2)});
}`

also, slowing the "animation" by adding `sleep(0.5)`

**Comment by mirisr** [comment]
Passing to marco to integrate into original notebook

**Comment by marcoct** [comment]
Integrated.
