### ISSUE TITLE
Augment goal infernce trace rendering to show waypoint

### ISSUE THREAD

**Issue by marcoct** [probcomp/GenExperimental.jl#27]
For use with `agent_waypoint_model`.

**Comment by marcoct** [comment]
This will involve modifying the Javascript trace rendering code to add a new circle for the `waypoint` if it exists in the given trace. It may not exist. It exists when `use-waypoint` is true and it does not exist when `use-waypoint` is false. The rendering should still run but simply not show the waypoint if it does not exist. Make it visually distinct from the other elements of the rendering.

Test by simulating some traces of `agent_waypoint_model` and rendering them in "tile" form (e.g. using `Figure` as used elsewhere in the notebook).

**Comment by mirisr** [comment]
I thought a purple would work... but it's too close to both the start and goal points... we can talk about it later. 

<img width="293" alt="screen shot 2017-06-22 at 8 30 43 pm" src="https://user-images.githubusercontent.com/3237465/27461733-dff5c630-5789-11e7-8580-f522d5e23ada.png">
<img width="263" alt="screen shot 2017-06-22 at 8 31 02 pm" src="https://user-images.githubusercontent.com/3237465/27461734-e0108074-5789-11e7-87aa-a9b320c87e03.png">

**Comment by mirisr** [comment]
closing for now

**Comment by mirisr** [comment]
Actually sending this to marco to put into the real notebook.

**Comment by marcoct** [comment]
Looks great, I'll add it now.

**Comment by marcoct** [comment]
Integrated in https://github.com/probcomp/gen-examples/commit/c0f423555f241c5d160e2b43ee4caf68f677a104
