### ISSUE TITLE
Goal Inference: Javascript Did NOT Render

### ISSUE THREAD

**Issue by mirisr** [probcomp/GenExperimental.jl#31]
Javascript did not render in notebook. 
<img width="878" alt="screen shot 2017-06-22 at 11 57 50 am" src="https://user-images.githubusercontent.com/3237465/27443731-0d297e82-5742-11e7-908d-e4218f61ab85.png">

**Comment by marcoct** [comment]
I forget, was this still an issue, or is it fixed?

**Comment by mirisr** [comment]
It was fixed by adding the right d3.min.js file. I'll close it now.
