### ISSUE TITLE
Goal Inference: Constrained Pts on Path Look Erroneous due to "crossing" obstacles

### ISSUE THREAD

**Issue by mirisr** [probcomp/GenExperimental.jl#34]
We need to explain why the paths look like they are going through walls. Make it clear that prior RRTs are being sampled and 'constrain' tries to fit the (7) contained points into that sampled path.

<img width="923" alt="screen shot 2017-06-22 at 2 24 50 pm" src="https://user-images.githubusercontent.com/3237465/27449485-975f54b4-5756-11e7-9202-276f7a8d7d15.png">

**Comment by mirisr** [comment]
Updated how the lines are drawn. We now draw the paths that the planner originally makes to show a better visualization of what's happening here. 
<img width="776" alt="screen shot 2017-06-23 at 2 26 01 pm" src="https://user-images.githubusercontent.com/3237465/27495500-1a2227e0-5820-11e7-9941-d9f3137b2a94.png">

Giving to Marco so he can add it to the original notebook.

**Comment by marcoct** [comment]
Integrated in https://github.com/probcomp/gen-examples/commit/a2226f8875e2ea98197ec3c50309832dda051cc2
