### ISSUE TITLE
Goal Inference: Code box does NOT compile due to renaming a variable 

### ISSUE THREAD

**Issue by mirisr** [probcomp/GenExperimental.jl#36]
In the SIR section, the code box after the agent_model_importance_sampling function. 

<img width="937" alt="screen shot 2017-06-22 at 2 51 20 pm" src="https://user-images.githubusercontent.com/3237465/27450722-992ed95a-575a-11e7-95a7-dfb0b45d3708.png">

**Comment by marcoct** [comment]
Fixed.
