### ISSUE TITLE
Goal Inference: Code box does NOT compile due to variable that does not exist

### ISSUE THREAD

**Issue by mirisr** [probcomp/GenExperimental.jl#37]
Running the dataset (created in SIR ) now in MH... (right when MH gets introduced) 

Variable 'points' is being called. 'points' does not exist. Should be 'dataset'
<img width="721" alt="screen shot 2017-06-22 at 2 56 10 pm" src="https://user-images.githubusercontent.com/3237465/27450901-36ab72ce-575b-11e7-9eca-871d0a9b03c5.png">

**Comment by marcoct** [comment]
Fixed.
