### ISSUE TITLE
Goal Inference: Missing Start and Goal icons on FireFox

### ISSUE THREAD

**Issue by mirisr** [probcomp/GenExperimental.jl#45]
<img width="952" alt="screen shot 2017-06-26 at 5 00 59 pm" src="https://user-images.githubusercontent.com/3237465/27560143-1f464698-5a91-11e7-9dc9-c6d63f153645.png">

**Comment by marcoct** [comment]
I believe I fixed this in https://github.com/probcomp/gen-examples/commit/e948e3988b75638673d88d69f55c1fbd5dba7b69. Tested and working in my version of Firefox (Linux, 64 bit, version 54).

**Comment by mirisr** [comment]
My Safari is that version as well. I can try it again.
